GoReleaser config and multi-platform image builds (#1052)
* GoReleaser config and multi-platform image builds

Using GoReleaser simplifies the build process substantially, as it
handles almost all the logic that needed to be in the makefile and the
pipelines themselves.

The one things that's missing from all this is a PAT to allow GoReleaser
to push to ghcr.io. That means it fails here (which is expected):

```
ERROR: failed to push ghcr.io/goss-org/goss:latest: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Agoss-org%2Fgoss%3Apull%2Cpush&service=ghcr.io: 403 Forbidden
```

Adding a PAT called 'GITHUB_TOKEN' as a secret would allow this to work
on the main repo.

Owing to how GoReleaser works, I added something so that generating the
.sha256 files for the {d,dc,k}goss scripts wouldn't cause GoReleaser to
treat the repo as dirty. It also encourages building archives rather
than attaching uncompressed binaries to releases.

Incidentally, this means that the goss images are now built with SBOMs.
It's straightforward to extend the configuration to also build packages
and generate SBOMs for the release artifacts too.

I believe this should mean the Travis CI pipelines can go away.

I'd also note that the pipeline described by docker-goss.yaml is broken
owing to aquasecurity/trivy-action's 0.24.0 tag no longer exists (likely
due to the issues with and attacks on Trivy over the past few months).
This new pipeline can do everything as far as release builds go, so I
think that could be trimmed down to just a simple build of the master
image on pushes to the master branch.

* Pull in some changes from my joss fork

* How to build goss with goreleaser

* Update install.sh to support the compressed binaries

* Copy the change in from #1068 adding x390x

Additionally, this adjust the architectures to fit the goreleaser
naming, which is closer to that of uname.

* Add linux/ppc64le to the build

Closes #1012.